services:
  luabla_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume for PostgreSQL data
    ports:
      - "8701:5432"
    environment:
      POSTGRES_DB: LuablaDB # Recommended to be called "LuablaDB"
      POSTGRES_USER: defaultuser
      POSTGRES_PASSWORD: defaultpassword
    networks:
      - luabla-network

  luabla:
    build: .
    command: sh -c "python manage.py makemigrations Authentication --noinput && python manage.py migrate Authentication --noinput && python manage.py makemigrations --noinput && python manage.py makemigrations Community --noinput && python manage.py makemigrations Chinese --noinput && python manage.py makemigrations English --noinput && python manage.py makemigrations Profile --noinput && python manage.py migrate --noinput && python manage.py makemigrations Welcome --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8700"
    volumes:
      - .:/app
    env_file:
      - Luabla/.env
    ports:
      - "8700:8700"
    depends_on:
      - luabla_db
    environment:
      - DEBUG= True # Show console and template errors for debugging (Set to 0/False of you´re a user, to 1/True if you´re a developer or tester).
      - DB_NAME= LuablaDB # Recommended to be called 'LuablaDB'
      - DB_USER= defaultuser # Set to 'postgres' user to use your 'by-default' PostgreSQL user.
      - DB_PASSWORD= defaultpassword 
      - DB_HOST= luabla_db # Luabla Database Container
      - DB_PORT= 5432 # Set to 5432 to use the 'by-default' port
    networks:
      - luabla-network

volumes:
  postgres_data:

networks:
  luabla-network:
    driver: bridge
