# Generated by Django 4.2.11 on 2025-06-30 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_shareable', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(default='deck_images/default_deck_image.jpg', null=True, upload_to='deck_images/')),
                ('downloads', models.IntegerField(default=0, null=True)),
                ('cards_quantity', models.IntegerField(default=0, null=True)),
                ('hsk_level', models.CharField(choices=[('HSK1', 'HSK 1'), ('HSK2', 'HSK 2'), ('HSK3', 'HSK 3'), ('HSK4', 'HSK 4'), ('HSK5', 'HSK 5'), ('HSK6', 'HSK 6')], default='HSK1', max_length=5, null=True)),
                ('language', models.CharField(default='ZH', max_length=2, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_deck_author', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='chinese_deck_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_shareable', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(default='deck_images/default_deck_image.jpg', null=True, upload_to='deck_images/')),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('IT', 'Italian'), ('DE', 'Deutsch'), ('PT', 'Portuguese'), ('RU', 'Russian')], default='EN', max_length=2, null=True)),
                ('downloads', models.IntegerField(default=0, null=True)),
                ('cards_quantity', models.IntegerField(default=0, null=True)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=5, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_author', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='deck_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JapaneseDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_shareable', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(default='deck_images/default_deck_image.jpg', null=True, upload_to='deck_images/')),
                ('downloads', models.IntegerField(default=0, null=True)),
                ('cards_quantity', models.IntegerField(default=0, null=True)),
                ('jlpt_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], default='N5', max_length=5, null=True)),
                ('language', models.CharField(default='JP', max_length=2, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_deck_author', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='japanese_deck_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KoreanDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_shareable', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(default='deck_images/default_deck_image.jpg', null=True, upload_to='deck_images/')),
                ('downloads', models.IntegerField(default=0, null=True)),
                ('cards_quantity', models.IntegerField(default=0, null=True)),
                ('topik_level', models.CharField(choices=[('TOPIK-I-1', 'TOPIK-I-1'), ('TOPIK-I-2', 'TOPIK-I-2'), ('TOPIK-II-3', 'TOPIK-II-3'), ('TOPIK-II-4', 'TOPIK-II-4'), ('TOPIK-II-5', 'TOPIK-II-5'), ('TOPIK-II-6', 'TOPIK-II-6')], default='TOPIK-I-1', max_length=15, null=True)),
                ('language', models.CharField(default='KO', max_length=2, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korean_deck_author', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='korean_deck_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RussianFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('cyrillic', models.CharField(max_length=50)),
                ('transliteration', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_deck', to='Application.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KoreanFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('hangul', models.CharField(max_length=50)),
                ('romaji', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korean_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korean_deck', to='Application.koreandeck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JapaneseFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('kanji', models.CharField(blank=True, max_length=50, null=True)),
                ('kana', models.CharField(max_length=50)),
                ('romaji', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_deck', to='Application.japanesedeck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='Application.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChineseFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('hanzi', models.CharField(max_length=40, null=True)),
                ('pinyin', models.CharField(max_length=120, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_deck', to='Application.chinesedeck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
