# Generated by Django 4.2.11 on 2025-07-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chineseflashcard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='chineseflashcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='author',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='japanesedeck',
            name='author',
        ),
        migrations.RemoveField(
            model_name='japanesedeck',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='japaneseflashcard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='japaneseflashcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='koreandeck',
            name='author',
        ),
        migrations.RemoveField(
            model_name='koreandeck',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='koreanflashcard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='koreanflashcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='russianflashcard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='russianflashcard',
            name='deck',
        ),
        migrations.DeleteModel(
            name='ChineseDeck',
        ),
        migrations.DeleteModel(
            name='ChineseFlashcard',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.DeleteModel(
            name='JapaneseDeck',
        ),
        migrations.DeleteModel(
            name='JapaneseFlashcard',
        ),
        migrations.DeleteModel(
            name='KoreanDeck',
        ),
        migrations.DeleteModel(
            name='KoreanFlashcard',
        ),
        migrations.DeleteModel(
            name='RussianFlashcard',
        ),
    ]
