# Generated by Django 4.2.11 on 2025-06-26 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RussianDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_shareable', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(default='deck_images/default_deck_image.jpg', null=True, upload_to='deck_images/')),
                ('downloads', models.IntegerField(default=0, null=True)),
                ('cards_quantity', models.IntegerField(default=0, null=True)),
                ('language', models.CharField(default='RU', max_length=2, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_deck_author', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='russian_deck_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RussianFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('cyrillic', models.CharField(max_length=50)),
                ('transliteration', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_deck', to='Application.russiandeck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JapaneseFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('kanji', models.CharField(blank=True, max_length=50, null=True)),
                ('kana', models.CharField(max_length=50)),
                ('romaji', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_deck', to='Application.japanesedeck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='Application.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChineseFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('hanzi', models.CharField(max_length=40, null=True)),
                ('pinyin', models.CharField(max_length=120, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_deck', to='Application.chinesedeck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
