# Generated by Django 5.1.1 on 2024-10-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_remove_cn_deck_author_remove_cn_deck_owners_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='word',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='hanzi',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='pinyin',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='language',
            field=models.CharField(max_length=30),
        ),
    ]
