# Generated by Django 4.2.11 on 2025-06-26 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0002_russiandeck_russianflashcard_japaneseflashcard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoreanDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_shareable', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(default='deck_images/default_deck_image.jpg', null=True, upload_to='deck_images/')),
                ('downloads', models.IntegerField(default=0, null=True)),
                ('cards_quantity', models.IntegerField(default=0, null=True)),
                ('topik_level', models.CharField(choices=[('TOPIK I - 1', 'TOPIK I - 1'), ('TOPIK I - 1', 'TOPIK I - 1'), ('TOPIK II - 3', 'TOPIK II - 3'), ('TOPIK II - 4', 'TOPIK II - 4'), ('TOPIK II - 5', 'TOPIK II - 5'), ('TOPIK II - 6', 'TOPIK II - 6')], default='TOPIK I - 1', max_length=15, null=True)),
                ('language', models.CharField(default='KO', max_length=2, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korean_deck_author', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='korean_deck_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KoreanFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('hangul', models.CharField(max_length=50)),
                ('romaji', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korean_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korean_deck', to='Application.koreandeck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='russianflashcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_deck', to='Application.deck'),
        ),
        migrations.DeleteModel(
            name='RussianDeck',
        ),
    ]
