# Generated by Django 5.1.1 on 2024-10-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_card_word_alter_card_hanzi_alter_card_pinyin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cefr_level',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='hsk_level',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
