# Generated by Django 5.1.3 on 2024-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_deck_cefr_level_alter_deck_hsk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(default='Let´s learn these!'),
        ),
    ]
