# Generated by Django 4.2.11 on 2025-06-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_alter_koreandeck_topik_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koreandeck',
            name='topik_level',
            field=models.CharField(choices=[('TOPIK-I-1', 'TOPIK-I-1'), ('TOPIK-I-2', 'TOPIK-I-2'), ('TOPIK-II-3', 'TOPIK-II-3'), ('TOPIK-II-4', 'TOPIK-II-4'), ('TOPIK-II-5', 'TOPIK-II-5'), ('TOPIK-II-6', 'TOPIK-II-6')], default='TOPIK-I-1', max_length=15, null=True),
        ),
    ]
