# Generated by Django 4.2.11 on 2025-07-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Decks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='japaneseflashcard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='japaneseflashcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='koreanflashcard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='koreanflashcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='russianflashcard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='russianflashcard',
            name='deck',
        ),
        migrations.DeleteModel(
            name='ChineseFlashcard',
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.DeleteModel(
            name='JapaneseFlashcard',
        ),
        migrations.DeleteModel(
            name='KoreanFlashcard',
        ),
        migrations.DeleteModel(
            name='RussianFlashcard',
        ),
    ]
