# Generated by Django 5.1.1 on 2024-11-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_picked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
