# Generated by Django 5.1.3 on 2024-12-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_user_language_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Hi! I am using Luabla...', null=True),
        ),
    ]
