# Generated by Django 4.2.11 on 2025-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_user_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='language_picked',
            new_name='has_picked_language',
        ),
        migrations.AddField(
            model_name='user',
            name='has_valid_email',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
