# Generated by Django 4.2.11 on 2025-07-06 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Decks', '0002_remove_flashcard_author_remove_flashcard_deck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RussianFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('cyrillic', models.CharField(max_length=50)),
                ('transliteration', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_deck', to='Decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KoreanFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('hangul', models.CharField(max_length=50)),
                ('romaji', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korean_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korean_deck', to='Decks.koreandeck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JapaneseFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('kanji', models.CharField(blank=True, max_length=50, null=True)),
                ('kana', models.CharField(max_length=50)),
                ('romaji', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_deck', to='Decks.japanesedeck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='Decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChineseFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('hanzi', models.CharField(max_length=40, null=True)),
                ('pinyin', models.CharField(max_length=120, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_deck', to='Decks.chinesedeck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
